"use client"
import type { Metadata } from 'next'
import './globals.css'
import Head from 'next/head'
import { ContextProvider } from '@/contexts/ContextProvider'
import { TheHeader } from '../components/TheHeader'
require('@solana/wallet-adapter-react-ui/styles.css');

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
  params: { locale }
}: {
  children: React.ReactNode,
  params: any
}) {

  console.log(' children: ', children)
  return (
    <html lang={locale}>
      <body suppressHydrationWarning={true}>
        <Head>
          <title>Solana Scaffold Lite</title>
        </Head>

        <ContextProvider>
          <div className="flex flex-col h-screen">
            <TheHeader />
            <div>
              {children}
            </div>
          </div>
        </ContextProvider>

      </body>
    </html>
  );
}
